### ISSUE TITLE
Fix "error: [Errno 98] Address already in use" exposed during testing

### ISSUE THREAD

**Issue by junchaowu** [uber/tchannel-python#111] opened 2015-08-12 23:43 UTC
https://travis-ci.org/uber/tchannel-python/jobs/85838961

**Comment by blampe** [comment] 2015-08-12 23:49
@junchaowu please provide enough context on these issues to make them actionable. Someone else should be able to look at this and know what to do.

**Comment by breerly** [comment] 2015-10-20 00:22
duplicate of 256

**Closed** 2015-10-20 00:22 UTC
Labels: bug
